# PANDAS

vertical arrangement of data is called as seires

1.   A series is one dimensional array capable of holding any data type

## CREATING A SERIES

In [3]:
import numpy as np
import pandas as pd

In [4]:
labels =['a','b','c']
my_list=[10,20,30]
arr=np.array([20,40,60])
d={1:10,2:20,3:30}

In [5]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(data=arr,index=d)

1    20
2    40
3    60
dtype: int64

In [8]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

## CREATING DATAFRAMES

In [9]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)

In [10]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df_2=pd.DataFrame(data_list)
df_2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [12]:
#adding column to the dataframe of list
col = ['name','age','city','salary']
df_2.columns=col
df_2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000



1.  If you observe in dictionary pd.dataframes gives directly column wise arranged data bcoz dictionary has key ,values
2.   But when it comes to list  there are no  keys but still
we got data arranged into columns ..here the imp point to be noted is  it is not a list its lists of lists and if lists of lists come into pandas it always arranges data as it is in the list

In [13]:
# adding columns to RAWdata which doesnt have any columns
df_3=pd.DataFrame(data_list,columns=['name','age','city','salary'])
df_3

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selecting and Indexing of columns

In [14]:
df_2['age']

0    28
1    34
2    29
3    42
Name: age, dtype: int64

In [15]:
#if we want to target two columns
df_2[['salary','city']]

   salary      city
0   65000  New York
1   70000     Paris
2   62000    Berlin
3   85000    London

# Creating a new columns in exisitng DataFrame

In [16]:
df_2['designation']=['doctor','engineer','manager','hr']
df_2

    name  age      city  salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000     manager
3  Linda   42    London   85000          hr

# Removing column

In [17]:
df_2.drop('designation',axis=1)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df_2

    name  age      city  salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000     manager
3  Linda   42    London   85000          hr

In [19]:
#As you can see designation is not removed still that implies drop creates a copy and removes the column to remove permenantly we use this method
df_2.drop('designation',axis=1,inplace=True)
df_2
#now it is removed from orginal df_2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
#to remove multiple columns from df_2
df_2.drop(['salary','age'],axis=1)

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [21]:
  #removing rows
df_2.drop(0,axis=0)

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

# Selecting Rows in DataFrame

In [22]:
df_2.loc[[0,1]]

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [23]:
df_2.loc[0]

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [24]:
#how can we select a portion of rows in dataframe
df_2.loc[[0,1]][['name','salary']]

   name  salary
0  John   65000
1  Anna   70000

## CONDITIONAL SELECTION

In [25]:
df_2[df_2['age']>=29]

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [28]:
df_2[(df_2['age']>29) & (df_2['salary']>40000)]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000